### ISSUE TITLE
DevEdition theme change doesn't work since the DevTools aren't listening for the pref change

### ISSUE THREAD

**Issue by mnoorenberghe** [mnoorenberghe/mozscreenshots#25]
@bgrins - It seems like you mentioned this in [bug 1110952](https://bugzilla.mozilla.org/show_bug.cgi?id=1110952#c4) and [bug 1111047](https://bugzilla.mozilla.org/show_bug.cgi?id=1111047) was filed to fix it.

**Comment by bgrins** [comment]
Do you mean changing the devtools theme color isn't changing DE theme from light to dark, or that applying the DE theme isn't causing the browser's theme to change?

**Comment by mnoorenberghe** [comment]
STR:
1) open about:config
2) open devtools
3) change the devtools.theme pref

Expected result:
Theme changes in devtools

Actual result:
Only DevEdition browser theme changes

-- 
Sent from my phone

**Comment by bgrins** [comment]
Oh yeah, good point.   Bug 1111047 is the right place to point to for this.  I'll take a look at that

**Comment by mnoorenberghe** [comment]
Tracked in [bug 1111047](https://bugzilla.mozilla.org/show_bug.cgi?id=1111047)
