### ISSUE TITLE
Should paginate through /jobdetail/ endpoint

### ISSUE THREAD

**Issue by wlach** [mnoorenberghe/mozscreenshots#28]
Currently mozscreenshots just hits the /jobdetail/ endpoint once under the assumption that it will retrieve all the data in one go (https://github.com/mnoorenberghe/mozscreenshots/blob/621b194/web/compare.js#L144). However, it should actually be paginating through results, using the "next" link in the JSON to make sure all the objects are retrieved. Example of what the JSON would look like in this case (artificially setting a low limit to force pagination):

https://treeherder.mozilla.org/api/jobdetail/?repository=mozilla-inbound&limit=5&job_id__in=32383690,32383691,32383692,32383693,32383694,32383695,32383696,32383697,32383698,32383699,32383700,32383701,32383702,32383703,32383704,32383705,32383706,32383707,32383708,32383709,32383710,32383711,32383712,32383713,32383714,32383715,32383716,32383717,32383718,32383719,32383720,32383721,32383722,32383723,32383724,32383725

**Comment by wlach** [comment]
Just in case that link expires, here's what the JSON looks like:

```json
{
    "count": 105,
    "next": "https://treeherder.mozilla.org/api/jobdetail/?job_id__in=32383690%2C32383691%2C32383692%2C32383693%2C32383694%2C32383695%2C32383696%2C32383697%2C32383698%2C32383699%2C32383700%2C32383701%2C32383702%2C32383703%2C32383704%2C32383705%2C32383706%2C32383707%2C32383708%2C32383709%2C32383710%2C32383711%2C32383712%2C32383713%2C32383714%2C32383715%2C32383716%2C32383717%2C32383718%2C32383719%2C32383720%2C32383721%2C32383722%2C32383723%2C32383724%2C32383725&limit=5&offset=5&repository=mozilla-inbound",
    "previous": null,
    "results": [
        {
            "job_id": 32383690,
            "job_guid": "52b3f42581318e53b7150e94b98d496eda86cbf8",
            "title": "marionette",
            "value": "659/0/29\r",
            "url": null
        },
       ...
```

**Comment by mnoorenberghe** [comment]
Yeah, it makes the code more complicated to fetch `next` so I was trying to avoid doing this. Is it actually missing data in practice? I set high limits on queries to avoid needing to do another request.

**Comment by wlach** [comment]
I'm not sure. :) The current limit for number of objects returned is 2000. I don't think there is a giant rush to fix this, though it would be nice to do so at some point.

**Comment by mnoorenberghe** [comment]
Are you talking about the default limit if none is specified or the upper bound?

**Comment by wlach** [comment]
IIRC the default is currently the same as the limit, which is 2000.

**Comment by mnoorenberghe** [comment]
I'm fine with lowering the default in TH if I can continue to limit to 2000. Is that what you want?

**Comment by wlach** [comment]
With cursor pagination (which we're moving to for performance reasons), it's not possible to set an arbitrary limit from the client. If you don't have time to handle pagination on your end, we can just keep the default as it is.

**Comment by mnoorenberghe** [comment]
I stopped using jobdetail in #43
