### ISSUE TITLE
Switch from Treeherder /resultset/ endpoint to /push/

### ISSUE THREAD

**Issue by edmorley** [mnoorenberghe/mozscreenshots#41]
Hi!

Treeherder has switched to using the terminology "push" over "resultset", and as part of that work added a new `/push/` endpoint to replace `/resultset/`. Checking the access logs I see mozscreenshots is using `/resultset/` - would it be possible to switch over so we can remove it soon (ref bug 1437719)? (the two endpoints are identical aside from URL)

Many thanks :-)

cc @camd @sarah-clements

**Comment by edmorley** [comment]
Thank you :-)

**Comment by edmorley** [comment]
I don't suppose you know when this will be deployed?

**Comment by mnoorenberghe** [comment]
Oops, I forgot about that part. It's done now but the front-end JS may be cached for a bit.

**Comment by edmorley** [comment]
Working well - many thanks!
