### ISSUE TITLE
Deprecation notice: Treeherder /jobdetail/ endpoint for uploaded artifacts

### ISSUE THREAD

**Issue by sarah-clements** [mnoorenberghe/mozscreenshots#43]
Treeherder will stop storing uploaded artifacts in our JobDetail table since its a write intensive action and the artifacts can be retrieved via a taskcluster API. **Tentative deadline is April 30th**. 

What you'll need to do:

* Stop using the `/jobdetail/` endpoint to retrieve the uploaded artifacts.

* Instead, extract `task_id` and `retry_id` (synonymous with run) from any of the `/jobs/` endpoints (you won't need `job_id` anymore if you're only using it for the `/jobdetail/` endpoint).

* For UI code, you'll want to generate the url like [this](https://github.com/mozilla/treeherder/blob/e579399a6321b84701a316a4ff1f9ed2146e3d93/ui/helpers/url.js#L49) to retrieve artifacts (to retrieve all or by specific artifact value/name, depending on your needs). Use`https://firefox-ci-tc.services.mozilla.com` as the rootUrl and the taskcluster-lib-urls library.

* To format the code in the UI so it has the same keys as what the `/jobdetail/` endpoint returns you'll want a helper like [this one](https://github.com/mozilla/treeherder/blob/e579399a6321b84701a316a4ff1f9ed2146e3d93/ui/helpers/display.js#L47).

* For python code, the equivalent is [here](https://github.com/mozilla/treeherder/blob/master/treeherder/etl/taskcluster_pulse/handler.py#L357)

Let me know if you have questions :)

**Comment by mnoorenberghe** [comment]
I believe I addressed this now in 86fe20e and 28c033d. Let me know if I missed anything. It's a bit unfortunate I have to make an artifact request per job now whereas before I could get the artifacts for multiple jobs in one request. Hopefully it's not too many simultaneous requests to TC at once.

**Comment by sarah-clements** [comment]
> I believe I addressed this now in [86fe20e](https://github.com/mnoorenberghe/mozscreenshots/commit/86fe20e8d69b393b2d7dc2badfa06771be174a33) and [28c033d](https://github.com/mnoorenberghe/mozscreenshots/commit/28c033d964d216d83686fabf989cbb1b91055c6f). Let me know if I missed anything. 

I took a look and it seems fine. One thing you might want to look into is a `continuationToken`. We used that in `fetchArtifacts` in handler.py (see link in my initial post). More details here: https://docs.taskcluster.net/docs/reference/platform/queue/api#listArtifacts

>It's a bit unfortunate I have to make an artifact request per job now whereas before I could get the artifacts for multiple jobs in one request. Hopefully it's not too many simultaneous requests to TC at once.

We're not querying the taskcluster API in the same way you are, so your best bet is to ask someone in the #taskcluster matrix channel. You might also want to ask if you're better off using the taskcluster-lib-urls library rather than hard-coding the API url (due to any versioning changes in the future).
