### ISSUE TITLE
Comparison tool hits 500 Internal server error

### ISSUE THREAD

**Issue by gijsk** [mnoorenberghe/mozscreenshots#46]
The request for: 

```
https://treeherder.mozilla.org/api/project/mozilla-central/jobs/?count=2000&amp;exclusion_profile=false&amp;job_type_name=test-linux1804-64/opt-browser-screenshots-e10s&amp;result=success&amp;last_modified__gte=2021-05-26T10:19:52.273Z
```

hits a http 500 error, which then causes the console to log:

```
Uncaught (in promise) TypeError: jobsXHR.response is null
    fetchRecentScreenshotJobsWithScreenshots https://screenshots.mattn.ca/compare/compare.js?v=20200510:208
    populateSuggestedRevisions https://screenshots.mattn.ca/compare/compare.js?v=20200510:177
    init https://screenshots.mattn.ca/compare/compare.js?v=20200510:68
    <anonymous> https://screenshots.mattn.ca/compare/compare.js?v=20200510:658
    EventListener.handleEvent* https://screenshots.mattn.ca/compare/compare.js?v=20200510:658
```

**Comment by mnoorenberghe** [comment]
I fixed the original issue @gijsk reported in 1116cb0d8eb87e57ad7170ba67d615685de9007a but that only affects the autocomplete suggestions. It seems like `last_modified__gte` is no longer working.

@sfoster I'm not sure that's the issue as I'm pretty sure URLs like the latter are used when things are working. Ensure that there are actually artifacts on the `ss` job in TH, you probably still need to delete [this code](https://searchfox.org/mozilla-central/rev/ac36d76c7aea37a18afc9dd094d121f40f7c5441/browser/tools/mozscreenshots/head.js#61-64) if you're wanting images from the m-c tree of TH.
